export const TOGGLE_THERMOSTAT = 'TOGGLE_THERMOSTAT';

export const INCREASE_TEMP = 'INCREASE_TEMP';

export const DECREASE_TEMP = 'DECREASE_TEMP';

export const REGISTER_THERMOSTAT = 'REGISTER_THERMOSTAT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const CHECK_SESSION_UID = 'CHECK_SESSION_UID';

export const LIVE_TEMP_DATA_SUCCESS = 'LIVE_TEMP_DATA_SUCCESS';
