export const SAY_HELLO = 'SAY_HELLO';

export const TOGGLE_THERMOSTAT = 'TOGGLE_THERMOSTAT';

export const INCREASE_TEMP = 'INCREASE_TEMP';

export const DECREASE_TEMP = 'DECREASE_TEMP';

export const REGISTER_THERMOSTAT = 'REGISTER_THERMOSTAT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
